services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Adaniloff\KongUserBundle\:
        resource: '../../../../../vendor/adaniloff/kong-user-bundle/*'
        exclude: '../../../../../vendor/adaniloff/kong-user-bundle/{Entity}'

    Adaniloff\KongUserBundle\Service\KongApi:
        arguments:
            - '@eight_points_guzzle.client.api_kong'
