services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Adaniloff\KongUserBundle\:
        resource: '../../*'
        exclude: '../../{Entity}'

    kong_user.service.configuration:
        class: Adaniloff\KongUserBundle\Service\Configuration
        autowire: false
        arguments:
            - '%kong_user.config%'
